### ISSUE TITLE
Add autodux combineReducers version

### ISSUE THREAD

**Issue by alexesDev** [ericelliott/autodux#1]
This code does not look very good
```js
const rootReducer = combineReducers({
  orders: orders.reducer,
  ordersTable: ordersTable.reducer,
  selectedOrderIds: selectedOrderIds.reducer,
  map: map.reducer,
  now: map.reducer,
});
```
I suggest adding a custom autodux `combineReducers`:
```js
import { combineReducers } from 'autodux';

const rootReducer = combineReducers({
  orders,
  ordersTable,
  selectedOrderIds,
  map,
  now,
});
````

**Comment by alexesDev** [comment]
Perhaps it should be a separate package `autodux-extends` with a lot of dependencies like redux, reselect etc... and with helpers `combineReducers` and `createStructuredSelector`
```js
const selector = createStructuredSelector({
  map: map.selectors.getValue,
  now: map.selectors.getValue,
});
```

**Comment by ericelliott** [comment]
I'd put this in its own module, but it can be part of this repo if you want to PR.

**Comment by alexesDev** [comment]
At now autodux has one small dependency `lodash.curry` and this is awesome! If you add functions like `combineReducers`  then code will become less flexible :(

**Comment by ericelliott** [comment]
I just use named exports from all my reducers. For example:

```js
const {
  selectors: { getValue },
  actions: {
    increment,
    decrement
  },
  reducer,
  initial
} = counter;

export { getValue, increment, decrement, reducer, initial };
```

Then just import the stuff you want and use them directly, without all the dots.dots.dots. ;)
