### ISSUE TITLE
Autodux v1.0.6 installed

### ISSUE THREAD

**Issue by EmiPhil** [ericelliott/autodux#12]
Check out the dist files @ https://npm.runkit.com/autodux/dist/index.browser.js?t=1521221179499

`npm install autodux` installs autodux v2.0.0 in `package.json` but the dist file installed in node_modules has `/*! autodux v1.0.6 by undefined */` as the header.

I noticed this because you can't import `assign` or `id` from the autodux package on a fresh install.

**Comment by EmiPhil** [comment]
I'd make a pr request but I'm not seeing the build steps in the code repo. Hopefully this is a quick fix, though!

**Comment by ericelliott** [comment]
Working on it.

**Comment by EmiPhil** [comment]
Looks like this works from my end now, thanks.

What else needs to get done to bump the status of this project out of Early Release? I have some time to contribute if you are looking for external pr.

**Comment by ericelliott** [comment]
A few months of production use by some large teams would be good. Give it a try. File issues if you encounter bugs.
