### ISSUE TITLE
TypeScript support?

### ISSUE THREAD

**Issue by devlato** [ericelliott/autodux#18]
Hi,

do you plan to export some TypeScript/Flow definitions for the library?

**Comment by elijah-schow** [comment]
I was wondering the same thing.

**Comment by zvertovsek** [comment]
Any news on this one?

**Comment by ericelliott** [comment]
Looking for volunteers to lead the charge.

**Comment by andrii-maglovanyi** [comment]
Please take a look at this definitions draft:

```
declare module 'autodux' {
  interface LooseObject {
    [prop: string]: any,
    selectTime: any
  }

  interface ReducerSlice {
    initial: any,
    actions?: LooseObject,
    selectors?: {},
    slice: string
  }

  interface AutoReducerSlice {
    initial: any,
    reducer: {},
    slice: string,
    actions: LooseObject,
    selectors: LooseObject
  }

  const autodux: (arguments: ReducerSlice) => AutoReducerSlice;

  export default autodux
}
```

**Comment by ericelliott** [comment]
Please feel free to PR. Maybe @warrenv can test & review?

**Comment by theKashey** [comment]
Not looking great, and not quite "typed".

**Comment by ericelliott** [comment]
Still open to PRs. =)

**Comment by rssfrncs** [comment]
I came up with [this](https://www.typescriptlang.org/play?#code/PTAEEsHMDsHsCcCmoC0oAuALcBnUB3cAGyNAGNYBbZAM3itCQBMBXADwmlE1gAdxoKfIgBGAKERteCdJ3SJ4NAIZlkAQTLpwsaAB4AKqAC8oJdACeAPlABvMaAzneiAFyh9YgL5iB8xSvULDS0dUEl5aCY8YO0uOwcAbXD4JQAFel4cNxx0eAFIAF03M3MvMXQnZAAlRFZVeF0AZWNTCwAaUDUwtgiozs1YlrUggZ1rEwAKe1AcpXk3ZoAfUBZIxBoBWrbplRDoNzUxAEpja0axMRAISml4dDNZXiU78srOlnRYGJ0AMVWyJr3eTjUATWbzUCNIGIDq7WLFCwnIxnaEAbleznen0aiCIiE0CD+0ABULmiBBYOhC2hSOsJXRGOQOLxBPgOAA4ohoAo5ghAWSQTZQAkANaIcycUBi8ywGiQ6GmPAAA0giHQABIbABhJT8e5EcAAL0Qumllk8SqKoPBrnlZNpdvkovFBVA3gqmIAoj0Usz8Z82ZzuSkA-z5B1vbklH7WThBcLpZLpbLQJHfbj-QgcFbKWTqfbTqAaugWPBoPpKro09GM7HneYCtZvIz+nsOVyeaHScCWkL60nxSnu8glMqcGrNTq9UoDcbTeLzZa3BNnpB807pQUHcNzN8uO63tW9+3g7yGkfRtA472E+KBzK5Re2znVwjzNuRns3RcPSOPrBWA4ExdGmYcOmmJ9YjwcIuT6PtpWyXJ8itNR-z3IkSWhJtwIcasYwDaCelgvB4PFRC8mgQoDn-fDCX+MNyW-SwpgcPg2zceIHE4cAtBnddEHRLiZgNVRyPyQSuLhHQcAAfjcSDpIkhxxxZAi5NTH0a1UrMJO8B1OIEHjwD4x0BOmZgWHqNwajqBQGMsCSpKvA5LxPTs+WHawADINKjY8g3c89NOPSxphUzM2QWWsCICkMPKw0AfLw6Ks1is8GIjTTaLZULPAZK4oDgJBUAwbA8EIEhQBEZAmB0ZBCCwUBKAAlg8VMFhIGoaAgUGRAADpID60AmHxIhnmQZrWDagAiJR-0A6axAoK9ZCUYp5vYFpoFaogGWWnJbCcrJbHHdA1FVDpToAOSUahLqoNVsEogAJXVnG5JhPEulLItsVUzou0B-puu6gbVABZRA1CulhKGq+A3U8FolAmTicBE20AHJ5ByTHtgcQzeKIDjpgcaBbqxsb4Hgcw8dJ0xVTcABGAAmABmaYvp2VySaEnAHqwfJXt4d7amXG0OiecwiFgJQmDcERYFgPEzH0+mHCQEsyxmaF6e8BwueUn7js4hx-sh6HYfh5cHRZzmvCOC5LjAHh8GG2ACGQZJdlK5AWciUx4EgUA6AYMgWByBgjowD3eHoAA3cARpj33GDVUsPscZwZOd0xFfj5B+eoQWXtHYXRaYCA8BGjZM4azBTFAKWZbl0AU1-UAlUV5XEDMJUqo+SUsGQTWM9qUB45nFh6uQTAlALiBZF-SvJF4ESeKICVR07kp+5bH4uBMa0qVacxJaUaXZflqqlZV6AHXj2Ak5bVI8BMVJngpvwcF0A-Qo71ILRQCv26L0PACQbRvnPpfOWb5XQyWATgBITNXRuEfs-IAA). Most stuff should be inferred 👍🏼

**Comment by ericelliott** [comment]
I'm thinking of doing an update that will have TypeScript definitions in a `d.ts` file.
