### ISSUE TITLE
Is there a dist/cdn version of autodux? 

### ISSUE THREAD

**Issue by magbicaleman** [ericelliott/autodux#212]
I'm importing `autodux` into a project, which uses rollupjs to bundle my component but it's adding all of rambdajs, so it takes a 5kb and turns it into 66kb file.

I might have to figure out how to make adjustments to my rollupjs configuration, if there was a dist of this I guess I could treat it as an external dependency.

**Comment by ericelliott** [comment]
Sorry for the radio silence. We're not going to bundle this, but I'm thinking of building an updated version of autodux that should tree-shake better..
