### ISSUE TITLE
What's the best practice for creating actions that do not transform state?

### ISSUE THREAD

**Issue by magbicaleman** [ericelliott/autodux#213]
I'm not sure why I'm having a hard time with this but, I'm struggling to find a way to create an action that Saga can listen to, without autodux having to update the state. Without trying to create an action outside of my autodux. 

For example, if I'm creating a "REQUEST" action, without it setting any state, that my saga can listen to, but autodux isn't expecting to change the state. I want my saga to dispatch, and then update state based on request-response. 

Is this the solution? 

`actions: {
        startMarkRead: (state) => state,
}`

**Comment by ericelliott** [comment]
Yes.
