### ISSUE TITLE
Fail to try out autodux in browsers with native ESM support

### ISSUE THREAD

**Issue by dwiyatci** [ericelliott/autodux#25]
I wanted to quickly try autodux out in the browser and did something like:
```html
<script type="module">
  import autodux from 'https://unpkg.com/autodux@3.0.1/dist/index-esm.js';
  
  console.log(autodux);
</script>
```
...but it throws:
> ❌ Uncaught SyntaxError: The requested module 'https://unpkg.com/autodux@3.0.1/dist/index-esm.js' does not provide an export named 'default'

**Comment by ericelliott** [comment]
I published an update with a default export autodux@4.0.3 -- but I don't think that will solve the whole problem. Give it a try and see if it helps.
