### ISSUE TITLE
Please remove dependency on lowdash-fp

### ISSUE THREAD

**Issue by timothyarmes** [ericelliott/autodux#27]
Hi,

You're pulling in lowdash-fp for just one function (`get`). Is this really necessary? It adds a lot of code bloat for users of other libraries.

**Comment by ericelliott** [comment]
1. We use 2 functions, `get`, and `capitalize`.

2. We're using modular imports -- in other words, importing the minimum dependency to use the functions we use.

Are you sure this is contributing significant bloat? By how much, exactly?
