### ISSUE TITLE
How to properly combine\nest autodux?

### ISSUE THREAD

**Issue by irrvrsl** [ericelliott/autodux#29]
Hello! I've started to use `autodux` for a while, it's really convenient, but I'm facing a problem with nesting for `autodux` generated entities. Let's say I want to nest some sub features into feature:

```
import { combineReducers } from 'redux';
import { reducer as requests } from './features/requests';

// This is my 'manage' feature
export const reducer = combineReducers({
  requests,
});
```

Here is `autodux` for 'requests':

```
export const { actions, reducer, selectors, slice } = autodux({
  actions: {
    ...fetchActions,
  },
  initial: initialState,
  slice: 'requests', // For me this should sound like 'manage/requests'
});
```

If i combine reducers this way, generated selectors is looking for slice `state['requests']`, but actually slice in `state.manage.requests` . Also action types have namespace `requests/myAction`, but i want it to be `manage/requests/myAction`. Is there an autodux way for this kind of using? Or am I missing something in redux basics? I will be grateful for any help. Thanks!

**Comment by ericelliott** [comment]
What does your 'manage' reducer look like? Seems like you just need to wire up plumbing there, or you can go ahead and let `autodux` expect top-level billing and make it clear using a more detailed slice name like `slice: 'manage/requests'`.

**Comment by ericelliott** [comment]
You can override selectors to select whatever subslice you like in your `manageReducer`, but in the code you pasted, `manageReducer` is just an intermediary that serves no purpose. If you make the `requests` reducer a top-level reducer in your `rootReducer`, this problem should go away.

**Comment by irrvrsl** [comment]
Indeed, it is existing only for semantic purposes. I'm trying to keep redux state tree in sync with my file structure. Maybe it has no sense in term of redux.

Anyway, thanks for your help! Happy new year!
