### ISSUE TITLE
Webpack breaks with ES6

### ISSUE THREAD

**Issue by nuba** [ericelliott/autodux#3]
Hi @ericelliott,

Thanks for autodux, it's really nice and useful! :)

I know this is still in "developer preview mode", so what folows is more of a suggestion than a bug report.

Please consider releasing as ES5 too.

In a new project with @angular/cli: 1.2.6 the build breaks with

> ERROR in vendor.42b3b802a29f068797b9.bundle.js from UglifyJs
> Invalid assignment [/home/nuba/IdeaProjects/understudio-angular-quickstart/~/autodux/source/index.js:3,0][vendor.42b3b802a29f068797b9.bundle.js:20545,47]

And with @angular/cli we're quite limited when it comes to tweaking webpack's behaviour to add a preprocessor or something.

I worked around it by embedding autodux (as it's really small) in my ts code (which then had ES5 as target in tsconfig.json). But just calling `tsc --allowJs -t ES5 index.js --outFile index.ES5.js` did the trick ;)

Thanks, keep rocking!

Nuba

**Comment by ericelliott** [comment]
I think an ES5 bundle would be a fine addition, but it's not on my priority list, at the moment. I'm open to a pull request.

**Comment by ericelliott** [comment]
Released as 1.0.5
