### ISSUE TITLE
Selectors in nested reducer

### ISSUE THREAD

**Issue by louislebrault** [ericelliott/autodux#77]
My state look like this : `
{
  entities : {
    user : { ... }
  },
  login : { ... }
  ...
}
`
I have a dedicated reducer for my 'user' entity. Therefore, its selectors are not working : they are expecting to find user at the top level of my state, so the first parameter that my selectors receive is undefined.

Am i doing something wrong, or autodux can't generate me working selectors in that case ? 

This issue is related to #29, but my state shape is pretty common and i find disturbing that its not supported, i dont want to design my state around autodux limitations.

If its the second option, a potential workaround would be to be able to define slices like 'entities.user'. What do you think ?

**Comment by ericelliott** [comment]
If you build nested reducers like this, you need to create nested selectors to go along with them. In other words, instead of exporting your nested selectors directly for components to use, create base level selectors which select the user slice and delegate to the user selectors, and so on.
