### ISSUE TITLE
Payload returning undefined 

### ISSUE THREAD

**Issue by thomasjosephgreco** [ericelliott/autodux#8]
After doing a bit of testing, I'm still finding that the payload is returning undefined with the actions being generated. The action type is pulling through but payload is not. I recreated the `multiply` function in the README.md and the payload is still returning undefined in that instance. 

Here is an example of the autodux object.

```javascript
const tweetsSlice = autodux({
  slice: 'tweets',
  initial: defaultState,
  actions: {
    multiply: {
      reducer: (state, payload) => state.num * payload
    },
    submit: {
      reducer: (state, payload) =>  `state: ${state} payload: ${payload}`
    }
  },
  selectors: {
    getValue: id,
  }
});
```

Payload is returning undefined the the following tests:

```javascript
test('submit()', assert => {
  const msg = 'should have an action type and a payload.';
  const payload = {
    id: '12344',
    text: 'some text'
  };
  const actual = submit(payload);
  const expected = { type: submit().type, payload};  
  
  assert.same(actual, expected, msg);
  assert.end();
});
test('multiply', assert => {
  const msg = 'should multiply the state by the payload.';

  const payload = 3;
  const actual = multiply(payload);
  const expected = 3; // 3 * 1
  
  assert.same(actual, expected, msg);
  assert.end();
});
```

**Comment by ericelliott** [comment]
Currently, action creators don't pass the payload by default. If you want to pass through the payload, you need to specify an action creator, as in the example on the homepage:

```js
    multiply: {
      create: id,
      reducer: (state, payload) => state * payload
    }
```

The identity function will pass the arguments from the action creator straight through as the reducer payload.

**Comment by thomasjosephgreco** [comment]
Ahhh! That was tripping me up but total makes sense now 👍 . Thanks a lot. 

Also, let me know if you would ever like to me provide any examples for this redo or redux-dsm to help users see some of this in action 😎 . I definitely think this stuff is important so I'd love to help out where I could!
