### ISSUE TITLE
5.0.1 is pointing to src instead of dist

### ISSUE THREAD

**Issue by louislebrault** [ericelliott/autodux#93]
Hi. 

Autodux is breaking my application on IE11 because on latest version the module use /src instead of /dist.

If i downgrade to 5.0, autodux prevent me to build because of an error "Can't resolve './errors'".

I opened a PR, it should be enough to fix the issue : https://github.com/ericelliott/autodux/pull/94

**Comment by ericelliott** [comment]
How does it break on IE11, specifically? Is it throwing an error? Using unsupported syntax? Are you getting an error in your build step?

**Comment by louislebrault** [comment]
It is an unsupported syntax error(ES6), from the first arrow function the browser encounter.
