### ISSUE TITLE
Debug actions

### ISSUE THREAD

**Issue by krazyjakee** [ericelliott/autodux#95]
I cannot `debugger` or `console.log` inside an action. It does nothing and also swallows all errors.

How can I see what is going on inside an action?

```js
export const {
  reducer: platformReducer,
  actions: platformActions
} = autodux({
  slice: 'platforms',
  initial: {},
  actions: {
    setPlatforms: (_, payload) => {
      const newPlatform = {};
      console.log(payload);
      debugger;
      payload.forEach(g => newPlatforms[g.id] = g);
      return newPlatforms;
    }
  }
});
```

**Comment by ericelliott** [comment]
Are you sure your action is getting dispatched?

**Comment by krazyjakee** [comment]
Yes they are working as expected but I can't debug inside there. @ericelliott I must ask if you experience the same issue?

**Comment by ericelliott** [comment]
I have never seen this issue. Can you reproduce it on [Codesandbox.io](https://codesandbox.io)?

**Comment by ericelliott** [comment]
Another thing to try: Can you reproduce it when you try to reduce over an array of actions with `Array.prototype.reduce`?

**Comment by ericelliott** [comment]
I did notice that you're mutating an object that does not exist in your reducer. 

At the top of the reducer, you have:

```js
const newPlatform = {};
```

Then, when you try to use it, you use `newPlatforms` instead of `newPlatform`.
